name: Canary release

on: workflow_dispatch

jobs:
  canary-publish:
    name: Publish Packages (canary)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version
      - run: npm publish --access public --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
